# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/189e0a28-200d-496f-ab72-63f1ea1a08d5";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "ssd" "commit=120" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/189e0a28-200d-496f-ab72-63f1ea1a08d5";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "ssd" "commit=120" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/189e0a28-200d-496f-ab72-63f1ea1a08d5";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" "discard=async" "space_cache=v2" "ssd" "commit=120" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E85D-D71C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/87838928-6c70-4bfc-aaaa-8da0188cd193"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
