# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4d0624b7-e7ab-43b7-aecf-f5cf20df2355";
      fsType = "btrfs";
      options = [ "subvol=@nix" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4d0624b7-e7ab-43b7-aecf-f5cf20df2355";
      fsType = "btrfs";
      options = [ "subvol=@nix-home" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/4d0624b7-e7ab-43b7-aecf-f5cf20df2355";
      fsType = "btrfs";
      options = [ "subvol=@nix-var" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F74A-F5CD";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e28d46df-c5ba-4c45-9dc8-472cd9ef99da"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
